---
# tasks file for deploy_mysql_server
    - name: Updating repository
      apt : update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrading system
      apt : upgrade=dist force_apt_get=yes

    - name: install Mysql-server 8.0
      apt:
       name: '{{ item }}'
       update_cache: yes
      loop:
        - mysql-server
        - python3-mysqldb

    - name: Start MySQL service
      service: name=mysql state=started enabled=true

    - name: update mysql root password for all root accounts
      mysql_user:
       name: root
       host: '{{ item }}'
       login_user: root
       login_password: '{{ mysql_root_password }}'
       password: '{{ mysql_root_password }}'
       priv: '*.*:ALL'
      loop:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - localhost
      ignore_errors: true

    - name: copy .my.cnf file with root password credentials
      template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
      notify:
      - restart mysql
