version: '3'

services:
  db:
    image: novogrodsky/mysql:latest
    container_name: db
    restart: always
    env_file: db.env
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    links:
      - db

volumes:
  dbdata:
