name: CI

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Automatic deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check code
      - uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: novogrodsky/github-dockerfile
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
